apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fsm-backend-metrics
spec:
  podSelector:
    matchLabels:
      app: fsm-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 3000
