apiVersion: v1
kind: Secret
metadata:
  name: fsm-backend-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@postgres:5432/fsm_backend?schema=public"
  RATE_LIMIT_REDIS_URL: "redis://:password@redis:6379/0"
  JWT_ACCESS_SECRET: "replace-with-32-plus-char-secret"
  JWT_REFRESH_SECRET: "replace-with-32-plus-char-secret"
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_USER: "smtp-user"
  SMTP_PASS: "smtp-password"
  SMTP_FROM: "noreply@example.com"
